"""add_post_privacy_and_connections

Revision ID: 34f151a6d2dc
Revises: e2f7b0d9c4a6
Create Date: 2026-06-29 02:53:35.148345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f151a6d2dc'
down_revision: Union[str, None] = 'e2f7b0d9c4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follower_following')
    )
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'storage_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("CREATE TYPE postprivacy AS ENUM ('public', 'connections_only', 'private')")
    op.add_column('posts', sa.Column('privacy', sa.Enum('public', 'connections_only', 'private', name='postprivacy', create_type=False), nullable=True))
    op.execute("UPDATE posts SET privacy = 'public' WHERE privacy IS NULL")
    op.alter_column('posts', 'privacy', nullable=False)
    op.drop_constraint('webhook_events_event_id_key', 'webhook_events', type_='unique')
    op.drop_index('ix_webhook_events_event_id', table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index('ix_webhook_events_event_id', 'webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint('webhook_events_event_id_key', 'webhook_events', ['event_id'])
    op.alter_column('posts', 'privacy', nullable=True)
    op.drop_column('posts', 'privacy')
    op.execute("DROP TYPE postprivacy")
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'storage_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_table('connections')
    # ### end Alembic commands ###
