"""Add affiliate tracking tables

Revision ID: 91faaf5502c0
Revises: a3d23c19bc24
Create Date: 2026-07-08 18:13:42.523397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91faaf5502c0'
down_revision: Union[str, None] = 'a3d23c19bc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_codes_code'), 'affiliate_codes', ['code'], unique=True)
    op.create_index(op.f('ix_affiliate_codes_user_id'), 'affiliate_codes', ['user_id'], unique=False)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['affiliate_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_code_id'), 'affiliate_clicks', ['code_id'], unique=False)
    op.create_table('affiliate_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['affiliate_codes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_conversions_code_id'), 'affiliate_conversions', ['code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_conversions_code_id'), table_name='affiliate_conversions')
    op.drop_table('affiliate_conversions')
    op.drop_index(op.f('ix_affiliate_clicks_code_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_codes_user_id'), table_name='affiliate_codes')
    op.drop_index(op.f('ix_affiliate_codes_code'), table_name='affiliate_codes')
    op.drop_table('affiliate_codes')
    # ### end Alembic commands ###
